import type { DoNotContactRecord } from "./types";

const hubspotSourceNote =
  "Imported from HubSpot Signal / legacy Cross Brand advanced or closed-won deal preview on 2026-07-15. Internal reference only; do not use as external social proof without approved wording.";

function customer(id: string, companyName: string, domain: string): DoNotContactRecord {
  return {
    id: `hubspot-${id}`,
    companyName,
    domain,
    status: "EXISTING_CUSTOMER",
    product: "Signal",
    reason: "HubSpot closed-won or customer-linked Signal / Cross Brand deal.",
    notes: hubspotSourceNote,
  };
}

function opportunity(id: string, companyName: string, domain: string): DoNotContactRecord {
  return {
    id: `hubspot-${id}`,
    companyName,
    domain,
    status: "ACTIVE_OPPORTUNITY",
    product: "Signal",
    reason: "HubSpot advanced Signal / Cross Brand opportunity.",
    notes: hubspotSourceNote,
  };
}

export const hubspotSuppressionRecords: DoNotContactRecord[] = [
  customer("3dayblinds", "3 Day Blinds LLC", "3dayblinds.com"),
  customer("aircaraibes", "Air Caraibes", "aircaraibes.com"),
  customer("allianz", "ALLIANZ I.A.R.D.", "allianz.fr"),
  customer("appsflyer", "AppsFlyer", "appsflyer.com"),
  customer("april", "APRIL", "april.com"),
  customer("axa", "AXA", "axa.com"),
  opportunity("birkenstock", "Birkenstock USA, LP", "birkenstockusa.com"),
  customer("bluevine", "Bluevine", "bluevine.com"),
  customer("canadalife", "Canada Life", "canadalife.com"),
  customer("chloe", "Chloe", "chloe.com"),
  customer("dior", "Christian Dior Couture", "dior.com"),
  opportunity("cofidis", "Cofidis S.A. (succursale belge)", "cofidis.be"),
  customer("copaair", "Compania Panamena de Aviacion SA", "copaair.com"),
  customer("corsair", "Corsair", "corsair.fr"),
  customer("crocs", "Crocs", "crocs.com"),
  customer("databricks", "Databricks", "databricks.com"),
  customer("deel", "Deel, Inc.", "deel.com"),
  opportunity("dontegroup", "Donte Group, S.L.U.", "dontegroup.com"),
  customer("effy", "Effy Connect", "effy.fr"),
  opportunity("etam", "ETAM Lingerie S.A", "etam.com"),
  customer("europcar", "EUROPCAR MOBILITY GROUP", "europcar.fr"),
  customer("giftory", "Experience Gift Project Inc. d/b/a Giftory", "giftory.com"),
  customer("fendi", "Fendi Japan Headquarters", "fendi.com"),
  customer("flexicar", "Flexicar Internacional S.L.", "flexicar.es"),
  customer("fram", "FRAM", "fram.fr"),
  customer("francetoner", "FRANCE TONER", "francetoner.fr"),
  customer("freshworks", "Freshworks", "freshworks.com"),
  customer("headspace", "Headspace Inc.", "headspace.com"),
  customer("heytens", "Heytens Groupe", "heytens.com"),
  customer("iceweb", "IceWeb", "theiceweb.com"),
  customer("mixbook", "Interactive Memories, Inc. d/b/a Mixbook", "mixbook.com"),
  customer("interflora", "Interflora France", "interflora.fr"),
  customer("kitsch", "Kitsch LLC", "mykitsch.com"),
  customer("polene", "LA CADETTE - Polene Paris", "polene-paris.com"),
  customer("lamaisonconvertible", "LA MAISON CONVERTIBLE GROUPE MISWA", "lamaisonconvertible.fr"),
  customer("laredoute", "La Redoute S.A.", "laredoute.fr"),
  customer("bestmobilier", "LISA DESIGN - Best Mobilier", "bestmobilier.com"),
  opportunity("tagheuer", "TAG Heuer", "tagheuer.com"),
  customer("manutan", "MANUTAN International", "manutan.com"),
  customer("rugiet", "MSB Holdings, Inc. DBA Rugiet Health", "rugiet.com"),
  opportunity("navan", "Navan, Inc.", "navan.com"),
  customer("nayax", "Nayax Ltd.", "nayax.com"),
  customer("nickel", "Nickel", "nickel.eu"),
  customer("oscaro", "Oscaro.com", "oscaro.com"),
  customer("osklen", "Osklen", "osklen.com.br"),
  customer("planetart", "PlanetArt", "planetart.com"),
  customer("plarium", "Plarium Global Ltd", "plarium.com"),
  customer("playtika", "Playtika", "playtika.com"),
  customer("richemont", "Richemont", "richemont.com"),
  customer("samsung", "Samsung France", "samsung.com"),
  customer("sandro", "SANDRO", "sandro-paris.com"),
  opportunity("cotebrico", "SAS AIN (Cote Brico)", "cotebrico.fr"),
  customer("selectblinds", "SelectBlinds LLC", "selectblinds.com"),
  customer("serenaandlily", "Serena & Lily", "serenaandlily.com"),
  opportunity("sfr", "SFR S.A.S", "sfr.com"),
  customer("simplytoimpress", "Simply to Impress", "simplytoimpress.com"),
  customer("smartbox", "Smartbox", "smartbox.com"),
  customer("sofinco", "Sofinco", "sofinco.fr"),
  customer("stitchfix", "Stitch Fix, Inc.", "stitchfix.com"),
  customer("tartine", "Tartine Et Chocolat", "tartine-et-chocolat.com"),
  customer("tenable", "Tenable Inc", "tenable.com"),
  customer("thg", "THG PLC", "thg.com"),
  customer("trivago", "trivago", "trivago.com"),
  customer("ullapopken", "Ulla Popken", "ullapopken.nl"),
  customer("universalorlando", "Universal Orlando Resort", "universalorlando.com"),
  customer("universalstudioshollywood", "Universal Studios Hollywood", "universalstudioshollywood.com"),
  opportunity("wpp", "WPP", "wpp.com"),
  customer("xtb", "XTB S.A.", "xtb.fr"),
  customer("yotpo", "Yotpo Ltd.", "yotpo.com"),
  customer("apollo", "Zenleads Inc. DBA Apollo.io", "apollo.io"),
];
