import { z } from "zod";

import { searchDoNotContactRecords } from "@/features/do-not-contact/do-not-contact-policy";
import type { DoNotContactRecord } from "@/features/do-not-contact/types";
import { sequencePurposes, sequenceStepChannels } from "@/features/build-sequence/types";

import { PrismaBuildSequencePersistence } from "./build-sequence-service";
import { err, ok } from "./result";

const hubspotSequenceStepSchema = z.object({
  stepNumber: z.number().int().min(1).max(6),
  channel: z.enum(sequenceStepChannels),
  delay: z.string().trim().min(1).max(120),
  purpose: z.enum(sequencePurposes),
  subjectLine: z.string().trim().max(160).optional(),
  connectionRequest: z.string().trim().max(300).optional(),
  messageBody: z.string().trim().min(1).max(2500),
  cta: z.string().trim().max(300).optional(),
});

const pushSequenceSchema = z.object({
  companyName: z.string().trim().min(1).max(180),
  companyWebsite: z.string().trim().max(240).optional(),
  overallStrategy: z.string().trim().max(1500),
  selectedAngle: z.string().trim().max(160),
  persona: z.string().trim().max(160),
  steps: z.array(hubspotSequenceStepSchema).min(1).max(6),
  safetyNotes: z.array(z.string().trim().max(500)).default([]),
  sourceTitles: z.array(z.string().trim().max(240)).default([]),
  creatorId: z.string().trim().min(1).optional(),
});

export type PushSequenceToHubSpotInput = z.infer<typeof pushSequenceSchema>;

type HubSpotObject = {
  id: string;
  properties?: Record<string, unknown>;
};

type HubSpotSearchResponse = {
  results?: HubSpotObject[];
};

export type HubSpotPushClient = {
  searchCompany(input: { companyName: string; domain?: string }): Promise<HubSpotObject | null>;
  createCompany(input: { companyName: string; domain?: string }): Promise<HubSpotObject>;
  createNote(input: { companyId: string; body: string }): Promise<HubSpotObject>;
  createTask(input: { companyId: string; subject: string; body: string }): Promise<HubSpotObject>;
};

export type HubSpotPushPersistence = {
  getSuppressionRecords(): Promise<DoNotContactRecord[]>;
};

export type PushSequenceDependencies = {
  client?: HubSpotPushClient;
  persistence?: HubSpotPushPersistence;
};

function normalizeDomain(value?: string) {
  const cleaned = (value ?? "")
    .trim()
    .toLowerCase()
    .replace(/^https?:\/\//, "")
    .replace(/^www\./, "")
    .replace(/\/.*$/, "");
  return cleaned || undefined;
}

function isBlocked(records: DoNotContactRecord[], companyName: string, domain?: string) {
  const matches = [
    ...searchDoNotContactRecords(records, companyName),
    ...(domain ? searchDoNotContactRecords(records, domain) : []),
  ];
  return matches.find((match) => match.blocked);
}

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function noteBody(input: PushSequenceToHubSpotInput) {
  const steps = input.steps
    .map((step) => {
      const parts = [
        `<strong>Step ${step.stepNumber} - ${escapeHtml(step.channel)} - ${escapeHtml(step.delay)}</strong>`,
        step.subjectLine ? `<strong>Subject:</strong> ${escapeHtml(step.subjectLine)}` : "",
        step.connectionRequest
          ? `<strong>Connection request:</strong><br>${escapeHtml(step.connectionRequest)}`
          : "",
        `<strong>Body:</strong><br>${escapeHtml(step.messageBody).replaceAll("\n", "<br>")}`,
        step.cta ? `<strong>CTA:</strong><br>${escapeHtml(step.cta).replaceAll("\n", "<br>")}` : "",
      ].filter(Boolean);
      return parts.join("<br>");
    })
    .join("<hr>");

  const safety = input.safetyNotes.length
    ? `<p><strong>Safety notes:</strong><br>${input.safetyNotes.map(escapeHtml).join("<br>")}</p>`
    : "";
  const sources = input.sourceTitles.length
    ? `<p><strong>Sources:</strong><br>${input.sourceTitles.map(escapeHtml).join("<br>")}</p>`
    : "";

  return [
    `<p><strong>Signal generated sequence for ${escapeHtml(input.companyName)}</strong></p>`,
    `<p><strong>Strategy:</strong><br>${escapeHtml(input.overallStrategy).replaceAll("\n", "<br>")}</p>`,
    `<p><strong>Angle:</strong> ${escapeHtml(input.selectedAngle)}<br><strong>Persona:</strong> ${escapeHtml(input.persona)}</p>`,
    "<hr>",
    steps,
    safety,
    sources,
    "<p><em>Review before sending. This note was generated by Primelis Signal and was not sent automatically.</em></p>",
  ].join("");
}

export class HubSpotApiClient implements HubSpotPushClient {
  constructor(private readonly token = process.env.HUBSPOT_PRIVATE_APP_TOKEN) {}

  private async request<T>(path: string, init: RequestInit) {
    if (!this.token) {
      throw new Error("HUBSPOT_PRIVATE_APP_TOKEN is not configured.");
    }
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 10_000);
    try {
      const response = await fetch(`https://api.hubapi.com${path}`, {
        ...init,
        signal: controller.signal,
        headers: {
          Authorization: `Bearer ${this.token}`,
          "Content-Type": "application/json",
          ...(init.headers ?? {}),
        },
      });
      if (!response.ok) {
        const body = await response.text();
        throw new Error(`HubSpot API failed: ${response.status} ${body.slice(0, 300)}`);
      }
      return (await response.json()) as T;
    } catch (error) {
      if (error instanceof Error && error.name === "AbortError") {
        throw new Error("HubSpot API timed out. Nothing may have been created - check HubSpot before retrying.");
      }
      throw error;
    } finally {
      clearTimeout(timeout);
    }
  }

  async searchCompany({ companyName, domain }: { companyName: string; domain?: string }) {
    const filters = domain
      ? [{ propertyName: "domain", operator: "EQ", value: domain }]
      : [{ propertyName: "name", operator: "EQ", value: companyName }];
    const data = await this.request<HubSpotSearchResponse>("/crm/v3/objects/companies/search", {
      method: "POST",
      body: JSON.stringify({
        filterGroups: [{ filters }],
        properties: ["name", "domain"],
        limit: 1,
      }),
    });
    return data.results?.[0] ?? null;
  }

  async createCompany({ companyName, domain }: { companyName: string; domain?: string }) {
    return this.request<HubSpotObject>("/crm/v3/objects/companies", {
      method: "POST",
      body: JSON.stringify({
        properties: {
          name: companyName,
          ...(domain ? { domain } : {}),
        },
      }),
    });
  }

  async createNote({ companyId, body }: { companyId: string; body: string }) {
    const note = await this.request<HubSpotObject>("/crm/v3/objects/notes", {
      method: "POST",
      body: JSON.stringify({
        properties: {
          hs_timestamp: new Date().toISOString(),
          hs_note_body: body,
        },
      }),
    });
    await this.request<Record<string, never>>(
      `/crm/v4/objects/notes/${note.id}/associations/default/companies/${companyId}`,
      { method: "PUT" },
    );
    return note;
  }

  async createTask({ companyId, subject, body }: { companyId: string; subject: string; body: string }) {
    const task = await this.request<HubSpotObject>("/crm/v3/objects/tasks", {
      method: "POST",
      body: JSON.stringify({
        properties: {
          hs_timestamp: new Date().toISOString(),
          hs_task_subject: subject,
          hs_task_body: body,
          hs_task_status: "NOT_STARTED",
          hs_task_priority: "MEDIUM",
        },
      }),
    });
    await this.request<Record<string, never>>(
      `/crm/v4/objects/tasks/${task.id}/associations/default/companies/${companyId}`,
      { method: "PUT" },
    );
    return task;
  }
}

export async function pushSequenceToHubSpot(
  rawInput: unknown,
  dependencies: PushSequenceDependencies = {},
) {
  const parsed = pushSequenceSchema.safeParse(rawInput);
  if (!parsed.success) {
    return err("VALIDATION_ERROR", "HubSpot push input is malformed.");
  }

  const input = parsed.data;
  const domain = normalizeDomain(input.companyWebsite);
  const persistence = dependencies.persistence ?? new PrismaBuildSequencePersistence();
  const blocked = isBlocked(await persistence.getSuppressionRecords(), input.companyName, domain);
  if (blocked) {
    return err(
      "SUPPRESSION_BLOCKED",
      `${blocked.record.companyName} is blocked by Do Not Contact / customer suppression. Nothing was sent to HubSpot.`,
    );
  }

  const client = dependencies.client ?? new HubSpotApiClient();
  try {
    const company =
      (await client.searchCompany({ companyName: input.companyName, domain })) ??
      (await client.createCompany({ companyName: input.companyName, domain }));
    const body = noteBody(input);
    const note = await client.createNote({ companyId: company.id, body });
    const task = await client.createTask({
      companyId: company.id,
      subject: `Review Signal sequence - ${input.companyName}`,
      body: "Review the Signal generated sequence in the associated note before sending anything.",
    });

    return ok({
      companyId: company.id,
      noteId: note.id,
      taskId: task.id,
      companyUrl: `https://app.hubspot.com/contacts/0/company/${company.id}`,
    });
  } catch (error) {
    return err(
      "HUBSPOT_ERROR",
      error instanceof Error ? error.message : "HubSpot push failed.",
    );
  }
}
